"""
scraper.py — Fetches latest news from RSS feeds across 8 raw source categories.

Raw → Display category mapping:
  usa           → usa
  world         → world
  europe        → world
  australia     → world
  india         → india
  hindi         → india
  telugu        → telugu
  telugu_film   → telugu_film

YouTube videos and article media are handled by media_scraper.py.
Hypocrisy tweets are AI-generated by rewriter.py.
"""

import feedparser
import re
import logging

logger = logging.getLogger(__name__)

NEWS_SOURCES = {
    "usa": [
        {"name": "AP News",           "url": "https://feeds.apnews.com/rss/apf-topnews"},
        {"name": "NPR",               "url": "https://feeds.npr.org/1001/rss.xml"},
        {"name": "NBC News",          "url": "https://feeds.nbcnews.com/nbcnews/public/news"},
        {"name": "Washington Post",   "url": "https://feeds.washingtonpost.com/rss/national"},
        {"name": "Axios",             "url": "https://api.axios.com/feed/"},
        {"name": "Politico",          "url": "https://www.politico.com/rss/politicopicks.xml"},
    ],
    "world": [
        {"name": "BBC World",         "url": "http://feeds.bbci.co.uk/news/world/rss.xml"},
        {"name": "Al Jazeera",        "url": "https://www.aljazeera.com/xml/rss/all.xml"},
        {"name": "Reuters World",     "url": "https://feeds.reuters.com/reuters/worldNews"},
        {"name": "DW World",          "url": "https://rss.dw.com/rdf/rss-en-world"},
    ],
    "europe": [
        {"name": "Euronews",          "url": "https://feeds.feedburner.com/euronews/en/news"},
        {"name": "BBC Europe",        "url": "http://feeds.bbci.co.uk/news/world/europe/rss.xml"},
        {"name": "DW Europe",         "url": "https://rss.dw.com/rdf/rss-en-eu"},
        {"name": "The Guardian EU",   "url": "https://www.theguardian.com/world/europe-news/rss"},
    ],
    "australia": [
        {"name": "ABC Australia",     "url": "https://www.abc.net.au/news/feed/51120/rss.xml"},
        {"name": "The Guardian AU",   "url": "https://www.theguardian.com/australia-news/rss"},
        {"name": "SBS News",          "url": "https://www.sbs.com.au/news/feed"},
    ],
    "india": [
        {"name": "NDTV",              "url": "https://feeds.feedburner.com/ndtvnews-top-stories"},
        {"name": "Times of India",    "url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms"},
        {"name": "The Hindu",         "url": "https://www.thehindu.com/news/national/feeder/default.rss"},
        {"name": "India Today",       "url": "https://www.indiatoday.in/rss/1206514"},
        {"name": "Hindustan Times",   "url": "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"},
        {"name": "The Wire",          "url": "https://thewire.in/feed"},
    ],
    "hindi": [
        {"name": "BBC Hindi",         "url": "http://feeds.bbci.co.uk/hindi/rss.xml"},
        {"name": "NDTV Hindi",        "url": "https://feeds.feedburner.com/ndtvkhabar"},
        {"name": "Aaj Tak",           "url": "https://feeds.feedburner.com/aajtaklive"},
        {"name": "Navbharat Times",   "url": "https://navbharattimes.indiatimes.com/rssfeeds/226734/cms.rssfeeds.cms"},
        {"name": "Dainik Bhaskar",    "url": "https://www.bhaskar.com/rss-feed/1061/"},
    ],
    "telugu": [
        {"name": "Sakshi",            "url": "https://www.sakshi.com/rss.xml"},
        {"name": "TV9 Telugu",        "url": "https://tv9telugu.com/feed"},
        {"name": "NTV Telugu",        "url": "https://www.ntvtelugu.com/feed"},
        {"name": "Eenadu",            "url": "https://www.eenadu.net/telugu-news/rss"},
        {"name": "ABN Telugu",        "url": "https://www.andhrajyothy.com/rss.xml"},
        {"name": "10TV News",         "url": "https://www.10tv.in/rss.xml"},
    ],
    "telugu_film": [
        {"name": "123Telugu",         "url": "https://www.123telugu.com/feed"},
        {"name": "Filmibeat Telugu",  "url": "https://telugu.filmibeat.com/rss.xml"},
        {"name": "Tollywood.net",     "url": "https://www.tollywood.net/feed/"},
        {"name": "Gulte",             "url": "https://www.gulte.com/feed/"},
        {"name": "Telugu360",         "url": "https://www.telugu360.com/feed/"},
        {"name": "GreatAndhra",       "url": "https://www.greatandhra.com/feed/"},
    ],
}

CATEGORY_DISPLAY_MAP = {
    "usa":         "usa",
    "world":       "world",
    "europe":      "world",
    "australia":   "world",
    "india":       "india",
    "hindi":       "india",
    "telugu":      "telugu",
    "telugu_film": "telugu_film",
}

STRIP_HTML = re.compile(r"<[^>]+>")


def _clean(text: str) -> str:
    text = STRIP_HTML.sub("", text or "")
    return " ".join(text.split())[:600]


def _image(entry) -> str | None:
    if hasattr(entry, "media_content") and entry.media_content:
        return entry.media_content[0].get("url")
    if hasattr(entry, "enclosures") and entry.enclosures:
        for e in entry.enclosures:
            if "image" in e.get("type", ""):
                return e.get("href") or e.get("url")
    return None


def scrape_feed(source: dict, raw_category: str, max_items: int) -> list[dict]:
    try:
        feed = feedparser.parse(source["url"])
        items = []
        for entry in feed.entries[:max_items]:
            title   = _clean(entry.get("title", ""))
            summary = _clean(entry.get("summary", entry.get("description", "")))
            link    = entry.get("link", "")
            if not title or not link:
                continue
            items.append({
                "source_url":       link,
                "original_title":   title,
                "original_summary": summary,
                "source_name":      source["name"],
                "raw_category":     raw_category,
                "category":         CATEGORY_DISPLAY_MAP.get(raw_category, raw_category),
                "image_url":        _image(entry),
                "youtube_id":       None,
                "video_url":        None,
            })
        logger.info(f"  {source['name']}: {len(items)} items")
        return items
    except Exception as e:
        logger.warning(f"  Failed {source['name']}: {e}")
        return []


def scrape_all(max_per_source: int = 5) -> list[dict]:
    all_items = []
    for raw_category, sources in NEWS_SOURCES.items():
        logger.info(f"[{raw_category.upper()}]")
        for source in sources:
            all_items.extend(scrape_feed(source, raw_category, max_per_source))
    logger.info(f"Total scraped: {len(all_items)}")
    return all_items
